[2022-03-11 12:15:26,493] [logger.py|__console] [line:41] INFO    : 当前执行测试用例ID-> test_login001.4 ; 测试点-> 手机号或密码不匹配
[2022-03-11 12:15:27,410] [logger.py|__console] [line:41] INFO    : 检查点-> 认证失败,您还有9次重试机会。
原因分析：
用户名或密码错误
[2022-03-11 12:15:27,460] [logger.py|__console] [line:41] INFO    : 异常登录，返回实际结果是->: 认证失败,您还有9次重试机会。
原因分析：
用户名或密码错误
